### ISSUE TITLE
Intermittent CI failure in vsyscall_reverse_next-32

### ISSUE THREAD

**Issue by Keno** [rr-debugger/rr#3102]
E.g.

https://buildkite.com/julialang/rr/builds/144#b2c2cc07-693c-4e00-9bbf-b9c966991175
https://buildkite.com/julialang/rr/builds/142#d9214086-6287-458b-83f1-7c6099751105

The logs are uploaded to the buildkite artifact storage.

**Comment by Keno** [comment]
Ah, of course the trace isn't portable because we didn't pack it. @DilumAluthge can you point me to the instructions for entering the rootfs that we use on CI?

**Comment by DilumAluthge** [comment]
```
git clone https://github.com/JuliaCI/rootfs-images.git

cd rootfs-images

julia --project -e 'import Pkg; Pkg.instantiate()'

julia --project test_rootfs.jl --treehash $ROOTFS_TREEHASH --url $ROOTFS_URL
```

You get the values of `ROOTFS_URL` and `ROOTFS_TREEHASH` by looking at the [`pipeline.yaml`](https://github.com/rr-debugger/rr/blob/master/.buildkite/pipeline.yml#L12) file.

**Comment by DilumAluthge** [comment]
Also, you can do `julia --project test_rootfs.jl --help` to list all the possible command-line options for the `test_rootfs.jl` script.

**Comment by Keno** [comment]
There's some AMD vs Intel performance difference here. Locally on Intel, this test finishes in a few seconds, but on AMD systems, both locally and CI it takes a long time:
```
vsyscall_reverse_next-32 ..........................................   Passed  144.08 sec
```
That's long enough that a 2x increase would trigger the timeout. @staticfloat @DilumAluthge I assume the rr core-contention issue we're fixing for Julia CI applies here also since this runs on our queues?

**Comment by Keno** [comment]
> Actually, now that I think about it, it doesn't even necessarily need to compete with other rr jobs. Since each of these tests runs in their own trace directory, it's not using our usual contention negotiation mechanism. Let me see if I can fix that.

Never mind, I already fixed this back when I implemented this mechanism :) https://github.com/rr-debugger/rr/blob/878f756966c660a6e838cbf3516f953e586b9edc/src/test/util.sh#L143

**Comment by Keno** [comment]
Alright, let's wait until we broadly deploy https://github.com/JuliaCI/sandboxed-buildkite-agent/pull/5 then and then we can see if this goes away. If so, we can open a separate issue for the AMD slowness.

**Comment by staticfloat** [comment]
The cpuset worker configuration has now been broadly deployed; hammer away.

**Comment by DilumAluthge** [comment]
We still have the issue of the test taking twice as long to run on AMD CPUs versus Intel CPUs, right?

**Comment by Keno** [comment]
Yes, but I'll file a separate issue about that once we're done with this one, since it's unrelated to CI.

**Comment by Keno** [comment]
No dice ... https://buildkite.com/julialang/rr/builds/156#94a8e08c-2066-430c-83da-6653d2910bd8 - @staticfloat can you confirm that this did run on a worker that had he new cpuset code active?

**Comment by staticfloat** [comment]
I had deployed the feature, but not turned it on in the worker-local configuration.  :)

Additionally, we have a mixture of agent types; some agents specifically do not set themselves within a cpuset; those are `exclusive` workers, and only have a single buildkite process (and 128 cores) per machine.  If you explicitly want to avoid those, we can target the `cpuset_active=true` workers.

**Comment by staticfloat** [comment]
As a note; when I re-ran your build, it got scheduled on an `exclusive` worker, and it still [took 180s to run the `vsyscall_reverse_next-32` test](https://buildkite.com/julialang/rr/builds/156#3d1bc621-ac5a-4b7c-aa55-44946f3b885b/4177-4257).  So I don't think overloading the CPU cores is responsible for this test being slow.

**Comment by Keno** [comment]
We don't need the cpuset as long as there are no other rr processes running on the machine that are not part of the same container. Within a container the rr processes negotiate core access amongst themselves.

**Comment by Keno** [comment]
> As a note; when I re-ran your build, it got scheduled on an `exclusive` worker, and it still [took 180s to run the `vsyscall_reverse_next-32` test](https://buildkite.com/julialang/rr/builds/156#3d1bc621-ac5a-4b7c-aa55-44946f3b885b/4177-4257).

180s is within the expected range on an AMD CPU (and a separate issue - it's much faster on Intel). The test fails if it takes >300s.

**Comment by Keno** [comment]
I'm gonna call this one fixed by the combination of #3107, #3109 and the cpuset fixes to the infrastructure.

**Comment by DilumAluthge** [comment]
> ```
> git clone https://github.com/JuliaCI/rootfs-images.git
> cd rootfs-images
> julia --project -e 'import Pkg; Pkg.instantiate()'
> julia --project test_rootfs.jl --treehash $ROOTFS_TREEHASH --url $ROOTFS_URL
> ```
> 
> 
>      
>   
> 
> You get the values of `ROOTFS_URL` and `ROOTFS_TREEHASH` by looking at the [`pipeline.yaml`](https://github.com/rr-debugger/rr/blob/master/.buildkite/pipeline.yml#L12) file.
> 
> 
> Note: if you are looking at the CI run for a PR, you should get the `ROOTFS_URL` and `ROOTFS_TREEHASH` values from the `pipeline.yaml` on the PR branch (instead of the `master` branch).

FYI - I put these instructions into a separate issue: https://github.com/rr-debugger/rr/issues/3115

It might be worth [pinning](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) #3115 to make it easier to find.
